### ISSUE TITLE
Project 4 doesnt word 

### ISSUE THREAD

**Issue by firenose** [jatripp0/COSC241LabsAndProjects#1]
result = exTree.evaluate(); error

**Comment by firenose** [comment]
Exception in thread "main" java.lang.NumberFormatException: For input string: "("
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at collection.MyExpressionTree.evaluateHelper(MyExpressionTree.java:35)
	at collection.MyExpressionTree.evaluateHelper(MyExpressionTree.java:55)
	at collection.MyExpressionTree.evaluate(MyExpressionTree.java:27)
	at project.Project_t.test(Project_t.java:92)
	at main.Main.main(Main.java:12)
